include/tweedledum/algorithms/generic/rewrite.hpp
include/tweedledum/algorithms/mapping/relative_phase.hpp
include/tweedledum/io/write_quil.hpp
include/tweedledum/networks/dag_path.hpp
include/tweedledum/networks/gates/mct_gate.hpp
include/tweedledum/networks/netlist.hpp

This PR partly unifies the interface, adds a generic rewriting algorithm, and a mapping algorithm for Toffolis up to 3 controls. Also, `write_quil` is extended to support more quantum gates.

Interface, rewriting, and write QUIL

---

tests/CMakeLists.txt

Maybe there is a reason behind excluding this target, but I would prefer not to exclude it. Note that the target is additionally guarded by the variable `TWEEDLEDUM_TESTS` in the outer CMake-file.

build system: tests.

---

include/tweedledum/utils/parity_terms.hpp

This PR fixes a compile-time error in `extract_term`.

extract_term.

---

include/tweedledum/utils/parity_terms.hpp

Reverts boschmitt/tweedledum#8
Here, the intended behavior is to actively extract the term from the mapping. If the intention is to only find it and return it, then a new method must be created.

Revert "extract_term."

---

include/tweedledum/io/write_unicode.hpp

This PR add a ``fancy`` parameter to the ``write_unicode`` function. This parameter is ``true`` by default and the circuit is printed as:
```
┌───┐                    ┌───┐     ┌───┐
|0>──┤ H ├───────◯────●────●──┤ H ├──◯──┤ H ├
└───┘       │    │    │  └───┘  │  └───┘
┌───┐       │    │    │  ┌───┐  │  ┌───┐
|0>──┤ H ├───────●────●────┼──┤ H ├──◯──┤ H ├
└───┘       │    │    │  └───┘  │  └───┘
┌───┐┌───┐  │    │    │  ┌───┐┌─┴─┐┌───┐
|0>──┤ X ├┤ H ├──◯────┼────◯──┤ H ├┤ Z ├┤ H ├
└───┘└───┘  │    │    │  └───┘└───┘└───┘
┌───┐┌───┐┌─┴─┐┌─┴─┐┌─┴─┐          
|0>──┤ X ├┤ H ├┤ X ├┤ X ├┤ X ├──────────
└───┘└───┘└───┘└───┘└───┘          
```
When ``fancy`` is ``false``, the output is the old representation:
```
―――――H―――――――○―●―●―H―――――○―H―――――
―――――――H―――――●―●―――――H―――○―――H――― …
```

Improve write unicode

---

docs/algorithms/synthesis.rst
docs/algorithms/synthesis/diagonal_synth.rst
docs/references.bib
include/tweedledum/algorithms/synthesis/diagonal_synth.hpp
tests/CMakeLists.txt
tests/algorithms/synthesis/diagonal_synth.cpp

This PR uses GraySynth to implement a synthesis algorithm based on [[N. Schuch and J. Siewert, *PRL* **91** (2003), 027902]](https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.91.027902) that finds CNOT+Rz circuits for diagonal unitary matrices.

Synthesis of diagonal unitaries

---

include/tweedledum/algorithms/generic/rewrite.hpp
include/tweedledum/networks/gg_network.hpp
include/tweedledum/networks/netlist.hpp

This PR cleanup a bit of 'auto' abuse; It fixes a bug when adding gates using qubit labels: when adding gates using those functions the possibility of rewiring was not being taken into account. It also adds a new function 'emplace_gate' which forward arguments. 
CAUTION: when emplacing a new gate, the network assumes the user took rewire into consideration.

Improve networks interface

---

include/tweedledum/io/qasm.hpp
include/tweedledum/io/quil.hpp

I'm not convinced this is the best solution. But it's a jumping-off point.
This was prompted by tweedledum outputting pi with only 6 digits of precision, which is not great. I think the best solution would be to, where possible, output a symbolic representation which the quil compiler certainly understands (not sure about qasm).

Output full floating point precision for quil and qasm

---

.travis.yml
include/tweedledum/gates/gate_base.hpp
include/tweedledum/gates/gate_set.def
include/tweedledum/gates/mcmt_gate.hpp
include/tweedledum/gates/mcst_gate.hpp
include/tweedledum/networks/gg_network.hpp
include/tweedledum/utils/angle.hpp
include/tweedledum/views/pathsum_view.hpp
tests/CMakeLists.txt
tests/algorithms/decomposition/barenco.cpp
tests/algorithms/decomposition/dt.cpp
tests/algorithms/mapping/zdd_map.cpp
tests/algorithms/synthesis/cnot_patel.cpp
tests/algorithms/synthesis/dbs.cpp
tests/algorithms/synthesis/diagonal_synth.cpp
tests/algorithms/synthesis/esop_phase_synth.cpp
tests/algorithms/synthesis/gray_synth.cpp
tests/algorithms/synthesis/linear_synth.cpp
tests/algorithms/synthesis/stg.cpp
tests/algorithms/synthesis/tbs.cpp
tests/catch2/catch.hpp
tests/gates/gates.cpp
tests/gates/mcst_gate.cpp
tests/io/qasm.cpp
tests/io/quil.cpp
tests/io/write_projectq.cpp
tests/io/write_qpic.cpp
tests/networks/networks.cpp
tests/utils/angle.cpp
tests/views/pathsum_view.cpp

This PR allows the tweedledum to represent any single-qubit gates using a parameterizable U3. In the U3 gate the user can parametrize three angles (theta, phi and lambda). 
The PR also change the way angles are represented to allow better symbolic representation and manipulation.
Update Catch2 framework and improve all test cases using templates, this allows testing combinations of `networks` and `gates` types.
Lastly, due to an error with GCC and MacOS 10.14.4, I commented out these builds in the TravisCI configuration file.

Parameterizable single qubit gates

---

include/tweedledum/utils/parity_terms.hpp

With this change I can target standard g++ installations (even the default macos version) with just `-std=c++17`.

Don't use C++17's unordered_map::extract()

---

setup.py

The previous wheels were shipping with only the C++ module.

Fix `setup.py` to correctly build python wheels

---

include/tweedledum/Parser/tfc.h
python/tweedledum/ir/circuit.cpp
src/CMakeLists.txt
src/Parser/tfc.cpp
tests/CMakeLists.txt
tests/Parser/tfc.cpp

This is a simple file format used in the ["Reversible Logic Synthesis
Benchmarks Page."](http://webhome.cs.uvic.ca/~dmaslov/mach-read.html)
```rst
TFC parser
```

Simple parser for TFC file format.

---

.travis.yml

This commit adds a travis ci configuration to leverage travis for
building non-x86 precompiled linux binaries for pypi. It will require enabling
travis CI on the repo before we can test this.
```rst
Added binary wheel builds for aarch64, ppc64le, and s390x linux.
```

Add travis job for non-x86 linux builds

---

python/test/test_BoolFunction.py
python/test/test_ExpressionParser.py
python/tweedledum/bool_function_compiler/bool_function.py
python/tweedledum/bool_function_compiler/expression_parser.py
python/tweedledum/bool_function_compiler/function_parser.py
python/tweedledum/classical/mockturtle.cpp

Allow users to define variable order when parsing expressions for
oracles. For example:
```python
ExpressionParser("((A & C) | (B & D)) & ~(C & D)", var_order=["A", "B", "C", "D"])
```
Variables `A, B, C, and D` will be placed on qubits `0, 1, 2, and 3`,
respectively. If this was called without an order:
```python
ExpressionParser("((A & C) | (B & D)) & ~(C & D)")
```
Then variables will be placed on qubits in order of appearance. That is,
`A, B, C, and D` will be placed on qubits  `0, 2, 1, and 3`, respectively.
```rst
Specify variable order for expressions parser
```

Expr variables order

---

.github/workflows/coverage.yml

The codecov workflow was using old directory names.

Fix dir name 'lib' -> 'src'

---

python/tweedledum/bool_function_compiler/__init__.py

Two functions that can be quite handy when synthesizing oracles.  They
take as input a BoolFunction and synthesize it to either a bitflip or a
phaseflip circuit implementation of the function.
```python
from tweedledum.bool_function_compiler import BitVec, BoolFunction, phaseflip_circuit
def f(v0, v1, v2, v3 : BitVec(1)) -> BitVec(1):
return (v0 != v1) and (v2 != v3) and (v0 != v2) and (v1 != v3)
oracle_func = BoolFunction(f)
oracle_circuit = phaseflip_circuit(oracle_func, 'pkrm')
```
Result:
```
╭───╮     
__q3 : ┤ z ├──◯──
╰─┬─╯╭─┴─╮
__q2 : ──◯──┤ z ├
│  ╰─┬─╯
__q1 : ──◯────●──
│    │  
__q0 : ──●────◯──
```
```rst
Synthesis of bitflip and phaseflip circuits.
```

Synthesis of bitflip and phaseflip circuits.

---

.travis.yml
CMakeLists.txt
external/bill/bill/sat/interface/ghack.hpp
external/mockturtle/mockturtle/algorithms/equivalence_checking.hpp

Fix the build for `arm64`, `ppc64le` and `s390x`. There is a problem
on `bsat2`, which `mockturtle` uses for equivalent checking. I change
the solver to be used, but I should further investigate the reasons and
maybe integrate newer SAT solvers.

Fix the build for `arm64`, `ppc64le` and `s390x`

---

.gitattributes

The source language for tweedledum is C++ whereas GitHub's metric depicts OpenQASM to be the predominant source (which isn't true). This PR aims to fix this.

Updated linguist's calculation to better reflect source language metric on GitHub 

---

include/tweedledum/Synthesis/Synthesis.h
include/tweedledum/Synthesis/sat_linear_synth.h
include/tweedledum/Target/Device.h
python/tweedledum/synthesis/synthesis.cpp
src/CMakeLists.txt
src/Synthesis/sat_linear_synth.cpp
tests/CMakeLists.txt
tests/Synthesis/sat_linear_synth.cpp

This PR includes an initial implementation for a SAT-based linear
synthesis method that also works under coupling constraints.
```python
from tweedledum.target import Device
from tweedledum.synthesis import sat_linear_synth
path3 = Device.path(3)
linear_trans = [[1,1,1], 
[0,1,0], 
[0,0,1]]
circuit = sat_linear_synth(path3, linear_trans)
print(circuit)
```
Results:
```
__q2 : ──●─────────●──
╭─┴─╮     ╭─┴─╮
__q1 : ┤ x ├──●──┤ x ├
╰───╯╭─┴─╮╰───╯
__q0 : ─────┤ x ├─────
╰───╯     
```
In comparison, `stainer_gauss_synth`:
```
__q2 : ───────●─────────●───────
╭─┴─╮     ╭─┴─╮     
__q1 : ──●──┤ x ├──●──┤ x ├──●──
╭─┴─╮╰───╯╭─┴─╮╰───╯╭─┴─╮
__q0 : ┤ x ├─────┤ x ├─────┤ x ├
╰───╯     ╰───╯     ╰───╯
```
The method guarantees finding an optimum solution. However,
It scales horribly on the number …

SAT-based linear synthesis

---

python/tweedledum/bool_function_compiler/bool_function.py

One of the docstrings contained the text `/!\ This function can only parse a _very_ small and simple subset of`, which generates a warning `DeprecationWarning: invalid escape sequence \ `.
This PR fixes this by making the docstring a raw string.
@boschmitt 
No entry needed

fix warnings generated by escape sequence in docstring

---

.github/workflows/build_dev_wheels.yml
.github/workflows/build_wheels.yml
.github/workflows/python.yml
setup.cfg

This commit updates the supported python versions in the trove classifiers in the Python package metadata along with also updating the test and wheel build matrix to support Python versions 3.7 through 3.11. Python 3.6 which was previously supported has been dropped as it went EoL in December 2021. Python 3.11 was recently released on 10-24-2022 so it will be good to have precompiled binaries available for it.
```rst
The supported Python versions for tweedledum have changed to be 3.7, 3.8, 3.9, 3.10, and 3.11. Support for using
tweedledum with Python 3.6 has been dropped as that version of Python has gone end of life.
```

Add support for Python 3.11 and drop 3.6 support
